hub:
   port: 4444
   environments:
       - name:    "Firefox3 on Windows"
         browser: "*firefox"
       - name:	  "Firefox3.6 on Windows"
         browser: "*firefox"
       - name:    "Firefox on Windows"
         browser: "*firefox"
       - name:    "Firefox on OS X"
         browser: "*firefox"
       - name:    "IE on Windows"
         browser: "*iehta"
       - name:    "Firefox on Ubuntu"
         browser: "*firefox /usr/lib/firefox-3.5.8/firefox"
       - name:    "Firefox3.6 on Ubuntu"
         browser: "*firefox /usr/lib/firefox-3.5.8/firefox"
       - name:    "IE7 on Windows"
         browser: "*iehta"
       - name:    "IE8 on Windows"
         browser: "*iehta"
       - name:    "IE9 on Windows"
         browser: "*iehta"
       - name:    "Safari on OS X"
         browser: "*safari"
       - name:    "*firefox"
         browser: "*firefox"
       - name:    "*firefox3"
         browser: "*firefox3"
       - name:    "*chrome"
         browser: "*chrome"
       - name:    "*iexplore"
         browser: "*iexplore"
       - name:    "*iehta"
         browser: "*iehta"
       - name:    "*safari"
         browser: "*safari"
       - name:    "*opera"
         browser: "*opera"
       - name:    "*googlechrome"
         browser: "*googlechrome"
       - name:    "*firefoxproxy"
         browser: "*firefoxproxy"
       - name:    "*pifirefox"
         browser: "*pifirefox"
       - name:    "*iexploreproxy"
         browser: "*iexploreproxy"
       - name:    "*piiexplore"
         browser: "*piiexplore"
       - name:    "*safariproxy"
         browser: "*safariproxy"
