:server:
  :ip: 127.0.0.1

:db:
  :development:
    :adapter: mysql
    :encoding: utf8
    :database: cacique_dev
    :pool: 5
    :username: user
    :password: passwors
    :host: localhost
  :test:
    :adapter: mysql
    :encoding: utf8
    :database: cacique_test
    :pool: 5
    :username: user
    :password: password
    :host: localhost
  :production:
    :adapter: mysql
    :encoding: utf8
    :database: cacique_prod
    :pool: 5
    :username: user
    :password: password
    :host: localhost

:workling:
  :production: "127.0.0.1:22122"
  :development: "127.0.0.1:22122"
  :test: "127.0.0.1:22122"

:hub:
  :ip: 127.0.0.1
  :port: 4444
  :rest: "/"

:queue:
  :ip: 127.0.0.1
  :port: "22122"

:memcached:
  :ip: 127.0.0.1

:environment:
  :production:
    :ip: 127.0.0.1

:mannager:
  :port: 33133
